#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alluxio-worker
spec:
  selector:
    matchLabels:
      app: alluxio-worker
  template:
    metadata:
      labels:
        app: alluxio-worker
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        app: alluxio-worker
      containers:
        - name: alluxio-worker
          image: bbklab/alluxio-fuse:latest
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          command: ["/entrypoint.sh"]
          args: ["worker"]
          env:
          - name: ALLUXIO_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          envFrom:
          - configMapRef:
              name: alluxio-config
          ports:
          - containerPort: 29998
            name: rpc
          - containerPort: 29999
            name: data
          - containerPort: 29996
            name: web
          - containerPort: 30001
            name: job-rpc
          - containerPort: 30002
            name: job-data
          - containerPort: 30003
            name: job-web
          securityContext:
            privileged: true
          volumeMounts:
            - name: alluxio-ramdisk
              mountPath: /dev/shm
            - name: alluxio-domain
              mountPath: /opt/domain
            - name: alluxio-logs
              mountPath: /opt/alluxio/logs
            - name: dev-fuse
              mountPath: /dev/fuse
      restartPolicy: Always
      volumes:
        - name: alluxio-ramdisk
          emptyDir:
            medium: "Memory"
            sizeLimit: "2G"
        - name: alluxio-domain
          hostPath:
            path: /tmp/alluxio-worker-domain
            type: Directory
        - name: dev-fuse
          hostPath:
            path: /dev/fuse
        - name: alluxio-logs
          hostPath:
            path: /tmp/alluxio-logs
